### ISSUE TITLE
Default settings?

### ISSUE THREAD

**Issue by VincentOostelbos** [infinyte7/Write-Kanji#1]
I like to turn off the "kanji" and "outline" options for this deck, because I want to study it not just for the stroke order but also to remember the kanji themselves, and I like to teach myself to write the strokes not just in the right order but in approximately the right place in the grid, without being shown the strokes ahead of time.

However, the settings have these as on by default, and these settings are taken every time I start a new review session, which means that the first kanji that is shown always does get "spoiled" for me, because I haven't yet been able to change these settings for this review session. It also does not seem possible to access the settings when you are looking at the front of a card, only the back.

Would it be possible to allow the user to edit their default settings somehow? Presumably this could be done in the template or styling for the cards. Perhaps you could include instructions on how to achieve this in the readme on this repository?

Thank you.

**Comment by krmanik** [comment]
Thanks,
I will update it.

**Comment by krmanik** [comment]
Now default settings can be changed. Update deck. View for more
https://github.com/infinyte7/Write-Kanji/blob/master/README.md#turn-off-default-settings

**Comment by VincentOostelbos** [comment]
Thank you very much for the swift update! This is wonderful.
