### ISSUE TITLE
Writing component bug - integrating with pre-existing deck

### ISSUE THREAD

**Issue by gavieru** [infinyte7/Write-Kanji#4]
I was trying to integrate the writing component into a [pre-existing deck](https://ankiweb.net/shared/info/759825185) which has images and audio/voiceover that plays. Unfortunately, after dropping in the scripts you provided, as well as editing the templates, I wasn't able to get the writing component to work in the preview or in the actual decks. (Interestingly, I have to check the "Fill Empty Fields" option in the Card Types/Template view to be able to see the hanzi writer as well. Maybe I'm doing something wrong there as well?)

The above is on my Windows desktop. Ultimately, I'd love to use this on my AnkiDroid (mobile app) as well, but I know that doesn't have your scripts. My workaround is just using the whiteboard feature to draw onscreen and manually comparing for now.

**Smaller workable sample of above deck, download from WeTransfer: https://we.tl/t-NPsmo5FsdC**

![image](https://github.com/krmanik/Write-Kanji/assets/165058300/0dd1d0b8-f90c-437f-aad2-79418b5af4da)
![image](https://github.com/krmanik/Write-Kanji/assets/165058300/27f243ca-f60c-49c8-94cc-8e3ad1eb7ea8)

**Comment by krmanik** [comment]
I have updated the script try again.

The issue in above deck is that `Writing` field is used but it is empty, and it does not contain any kanji or kana. So, change it to `Kanji` filed which make it work.

```diff
-<div id='ch_kanji' class="text-color4">{{Writing}}</div>
+<div id='ch_kanji' class="text-color4">{{Kanji}}</div>

```

Above fix the issues, you may update script with latest changes (it is optional).
Read more [here](https://github.com/krmanik/Write-Kanji/tree/master/Add%20to%20Existing%20Deck%20(Kanji)).

**Comment by gavieru** [comment]
That fixed it, amazing! And works well on mobile. :D
